# Welcome to Jekyll!
#

# Site settings
title: Arosis 
description: |
  Aroma and color therapy for your stress zero life  
  with special therapist 
  instructed by [Jiin Woo](http://www.arosis.co.kr)
owner: Arosis (아로시스) # or company name
first_published: 2023 # if migrating another site, the year of your first publish
email: arosis.ly@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://arosis.co.kr" # the base hostname & protocol for your site

# Google Analytics by SEO 240310
google_analytics: G-EVBJNCDJ9H

social:
  twitter: https://twitter.com/<username>
  github: https://github.com/arosiss
  linkedin-square: https://linkedin.com/in/<username>
  facebook-official: https://facebook.com/<username>
  google-plus-square: https://plus.google.com/u/0/+<username>
  #email: /contact/
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
